[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "bundledrefs"
authors = [{name = "Alexander Carr", email = "jalexandercarr@gmail.com"}]
dynamic = ["version", "description"]
